custom/dumpsoftwareversions:
  - modules/nf-core/custom/dumpsoftwareversions/**

fastqc:
  - modules/nf-core/fastqc/**

snakemake:
  - modules/nf-core/snakemake/**

sratools/prefetch:
  - modules/nf-core/sratools/prefetch/**
