name: samtools_view
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # renovate: datasource=conda depName=bioconda/samtools
  - bioconda::samtools=1.19.2
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.19.1
