name: gatk4_germlinecnvcaller
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::gatk4=4.5.0.0
  - pip:
      # https://swift.rc.nectar.org.au/v1/AUTH_377/public/gatkPythonPackageArchive.zip
      - gatkPythonPackageArchive.zip
