---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "gxf2bed"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::gxf2bed=0.1.0"
