---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "kmc_kmc"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - kmer
  - counting
  - filter
tools:
  - "kmc":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Tools for efficient k-mer counting and filtering of reads based on k-mer content."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: "['GPL v3']"

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam,cram,sam}"
  - fasta:
      type: file
      description: fasta file
      pattern: "*.{fa,fasta}"
  - fastq:
      type: file
      description: fasta file
      pattern: "*.{fq,fastqq}"
  - kmc:
      type: file
      description: KMC file
      pattern: "*.kmc"
  

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@homonecloco"
